
var pageurl=window.location.search;if(pageurl=='?m2w'){addCookie('m2wcookie','1',0);}
function browserRedirect(){var sUserAgent=navigator.userAgent.toLowerCase();var bIsIpad=sUserAgent.match(/ipad/i)=="ipad";var bIsIphoneOs=sUserAgent.match(/iphone os/i)=="iphone os";var bIsMidp=sUserAgent.match(/midp/i)=="midp";var bIsUc7=sUserAgent.match(/rv:1.2.3.4/i)=="rv:1.2.3.4";var bIsUc=sUserAgent.match(/ucweb/i)=="ucweb";var bIsAndroid=sUserAgent.match(/android/i)=="android";var bIsCE=sUserAgent.match(/windows ce/i)=="windows ce";var bIsWM=sUserAgent.match(/windows mobile/i)=="windows mobile";if(bIsIpad||bIsIphoneOs||bIsMidp||bIsUc7||bIsUc||bIsAndroid||bIsCE||bIsWM){return true;}else{return false;}}
function addCookie(objName,objValue,objHours){var str=objName+"="+ escape(objValue);if(objHours>0){var date=new Date();var ms=objHours*3600*1000;date.setTime(date.getTime()+ ms);str+="; expires="+ date.toGMTString();}
document.cookie=str;}
function getCookie(objName){var arrStr=document.cookie.split("; ");for(var i=0;i<arrStr.length;i++){var temp=arrStr[i].split("=");if(temp[0]==objName)return unescape(temp[1]);}
return"";}
function ForDight(Dight,How){Dight=Math.round(Dight*Math.pow(10,How))/ Math.pow(10, How);return Dight;}
function checkNumber(e){var keynum=window.event?e.keyCode:e.which;if((48<=keynum&&keynum<=57)||keynum==8){return true;}else{return false;}}
function checkForFloat(obj,e){var isOK=false;var key=window.event?e.keyCode:e.which;if((key>95&&key<106)||(key>47&&key<60)||(key==110&&obj.value.indexOf(".")<0)||(key==190&&obj.value.indexOf(".")<0)||key==8||key==9||key==46||key==37||key==39){isOK=true;}else{if(window.event){e.returnValue=false;}else{e.preventDefault();}}
return isOK;}
function copyText(txt){window.clipboardData.setData("Text",txt);var d=dialog({content:'复制成功，可以通过粘贴来发送！'}).show();setTimeout(function(){d.close().remove();},2000);}
function ToggleCode(obj,codeurl){$(obj).children("img").eq(0).attr("src",codeurl+"?time="+ Math.random());return false;}
function checkAll(chkobj){if($(chkobj).text()=="全选"){$(chkobj).text("取消");$(".checkall").prop("checked",true);}else{$(chkobj).text("全选");$(".checkall").prop("checked",false);}}
function tabs(tabObj,event){var tabItem=$(tabObj).find(".tab-head ul li a");tabItem.bind(event,function(){tabItem.removeClass("selected");$(this).addClass("selected");var tabNum=tabItem.parent().index($(this).parent());$(tabObj).find(".tab-content").hide();$(tabObj).find(".tab-content").eq(tabNum).show();});}
function showWindow(obj){var tit=$(obj).attr("title");var box=$(obj).html();dialog({width:500,title:tit,content:box,okValue:'确定',ok:function(){}}).showModal();}
$.fn.smartFloat=function(){var position=function(element){var top=element.position().top,pos=element.css("position");var w=element.innerWidth();$(window).scroll(function(){var scrolls=$(this).scrollTop();if(scrolls>top){if(window.XMLHttpRequest){element.css({width:w,position:"fixed",top:55});}else{element.css({top:scrolls});}}else{element.css({position:pos,top:top});}});};return $(this).each(function(){position($(this));});};function SiteSearch(send_url,divTgs,channel_name){var strwhere="";if(channel_name!==undefined){strwhere="&channel_name="+ channel_name}
var str=$.trim($(divTgs).val());if(str.length>0&&str!="输入关健字"){window.location.href=send_url+"?keyword="+ encodeURI($(divTgs).val())+ strwhere;}
return false;}
function downLink(point,linkurl){if(point>0){dialog({title:'提示',content:"下载需扣除"+ point+"个积分<br />重复下载不扣积分，需要继续吗？",okValue:'确定',ok:function(){window.location.href=linkurl;},cancelValue:'取消',cancel:function(){}}).showModal();}else{window.location.href=linkurl;}
return false;}
function numConvert(obj){var maxAmount=parseFloat($("#hideAmount").val());var pointCashrate=parseFloat($("#hideCashrate").val());var currAmount=parseFloat($(obj).val());if(currAmount>maxAmount){currAmount=maxAmount;$(obj).val(maxAmount);}
var convertPoint=currAmount*pointCashrate;$("#convertPoint").text(convertPoint);}
function ExecDelete(sendUrl,checkValue,urlObj){if(!checkValue){dialog({title:'提示',content:'对不起，请选中您要操作的记录！',okValue:'确定',ok:function(){}}).showModal();return false;}
dialog({title:'提示',content:'删除记录后不可恢复，您确定吗？',okValue:'确定',ok:function(){$.ajax({type:"POST",url:sendUrl,dataType:"json",data:{"checkId":checkValue},timeout:20000,success:function(data,textStatus){if(data.status==1){var tipdialog=dialog({content:data.msg}).show();setTimeout(function(){tipdialog.close().remove();if($(urlObj)){location.href=$(urlObj).val();}else{location.reload();}},2000);}else{dialog({title:'提示',content:data.msg,okValue:'确定',ok:function(){}}).showModal();}},error:function(XMLHttpRequest,textStatus,errorThrown){dialog({title:'提示',content:'状态：'+ textStatus+'；出错提示：'+ errorThrown,okValue:'确定',ok:function(){}}).showModal();}});},cancelValue:'取消',cancel:function(){}}).showModal();}
function clickSubmit(sendUrl){$.ajax({type:"POST",url:sendUrl,dataType:"json",timeout:20000,success:function(data,textStatus){if(data.status==1){var d=dialog({content:data.msg}).show();setTimeout(function(){d.close().remove();location.reload();},2000);}else{dialog({title:'提示',content:data.msg,okValue:'确定',ok:function(){}}).showModal();}},error:function(XMLHttpRequest,textStatus,errorThrown){dialog({title:'提示',content:"状态："+ textStatus+"；出错提示："+ errorThrown,okValue:'确定',ok:function(){}}).showModal();}});}
function sendEmail(username,sendurl){if(username==""){dialog({title:'提示',content:'对不起，用户名不允许为空！',okValue:'确定',ok:function(){}}).showModal();return false;}
$.ajax({url:sendurl,type:"POST",timeout:60000,data:{"username":username},dataType:"json",success:function(data,type){if(data.status==1){var d=dialog({content:data.msg}).show();setTimeout(function(){d.close().remove();},2000);}else{dialog({title:'提示',content:data.msg,okValue:'确定',ok:function(){}}).showModal();}},error:function(XMLHttpRequest,textStatus,errorThrown){dialog({title:'提示',content:"状态："+ textStatus+"；出错提示："+ errorThrown,okValue:'确定',ok:function(){}}).showModal();}});}
var wait=0;function sendSMS(btnObj,valObj,sendUrl){if($(valObj).val()==""){dialog({title:'提示',content:'对不起，请填写手机号码后再获取！',okValue:'确定',ok:function(){}}).showModal();return false;}
$.ajax({url:sendUrl,type:"POST",timeout:60000,data:{"mobile":$(valObj).val()},dataType:"json",beforeSend:function(XMLHttpRequest){$(btnObj).unbind("click").removeAttr("onclick");},success:function(data,type){if(data.status==1){wait=data.time*60;time();var d=dialog({content:data.msg}).show();setTimeout(function(){d.close().remove();},2000);}else{$(btnObj).removeClass("gray").text("发送确认码");$(btnObj).bind("click",function(){sendSMS(btnObj,valObj,sendurl);});dialog({title:'提示',content:data.msg,okValue:'确定',ok:function(){}}).showModal();}},error:function(XMLHttpRequest,textStatus,errorThrown){$(btnObj).removeClass("gray").text("发送确认码");$(btnObj).bind("click",function(){sendSMS(btnObj,valObj,sendurl);});dialog({title:'提示',content:"状态："+ textStatus+"；出错提示："+ errorThrown,okValue:'确定',ok:function(){}}).showModal();}});function time(){if(wait==0){$(btnObj).removeClass("gray").text("发送确认码");$(btnObj).bind("click",function(){sendSMS(btnObj,valObj,sendurl);});}else{$(btnObj).addClass("gray").text("重新发送("+ wait+")");wait--;setTimeout(function(){time(btnObj);},1000)}}}
function AjaxInitForm(formObj,btnObj,isDialog,urlObj,callback){var argNum=arguments.length;alert("test");$(formObj).Validform({tiptype:3,callback:function(form){$(form).ajaxSubmit({beforeSubmit:formRequest,success:formResponse,error:formError,url:$(formObj).attr("url"),type:"post",dataType:"json",timeout:60000});return false;}});function formRequest(formData,jqForm,options){$(btnObj).prop("disabled",true);$(btnObj).val("提交中...");}
function formResponse(data,textStatus){if(data.status==1){$(btnObj).val("提交成功");if(isDialog==1){var d=dialog({content:data.msg}).show();setTimeout(function(){d.close().remove();if(argNum==5){callback();}else if(data.url){location.href=data.url;}else if($(urlObj).length>0&&$(urlObj).val()!=""){location.href=$(urlObj).val();}else{location.reload();}},2000);}else{if(argNum==5){callback();}else if(data.url){location.href=data.url;}else if($(urlObj)){location.href=$(urlObj).val();}else{location.reload();}}}else{dialog({title:'提示',content:data.msg,okValue:'确定',ok:function(){}}).showModal();$(btnObj).prop("disabled",false);$(btnObj).val("再次提交");}}
function formError(XMLHttpRequest,textStatus,errorThrown){dialog({title:'提示',content:'状态：'+ textStatus+'；出错提示：'+ errorThrown,okValue:'确定',ok:function(){}}).showModal();$(btnObj).prop("disabled",false);$(btnObj).val("再次提交");}}
function AjaxPageList(listDiv,pageDiv,pageSize,pageCount,sendUrl,defaultAvatar){InitComment(0);$(pageDiv).pagination(pageCount,{callback:pageselectCallback,prev_text:"« 上一页",next_text:"下一页 »",items_per_page:pageSize,num_display_entries:3,current_page:0,num_edge_entries:5,link_to:"javascript:;"});function pageselectCallback(page_id,jq){InitComment(page_id);}
function InitComment(page_id){page_id++;$.ajax({type:"POST",dataType:"json",url:sendUrl+"&page_size="+ pageSize+"&page_index="+ page_id,beforeSend:function(XMLHttpRequest){$(listDiv).html('<p style="line-height:35px;">正在狠努力加载，请稍候...</p>');},success:function(data){var strHtml='';for(var i in data){strHtml+='<li>'+'<div class="avatar">';if(typeof(data[i].avatar)!="undefined"){strHtml+='<img src="'+ data[i].avatar+'" />';}else{strHtml+='<img src="'+ defaultAvatar+'" />';}
strHtml+='</div>'+'<div class="inner">'+'<p>'+ unescape(data[i].content)+'</p>'+'<div class="meta">'+'<span class="blue">'+ data[i].user_name+'</span>\n'+'<span class="time">'+ data[i].add_time+'</span>'+'</div>'+'</div>';if(data[i].is_reply==1){strHtml+='<div class="answer">'+'<div class="meta">'+'<span class="right time">'+ data[i].reply_time+'</span>'+'<span class="blue">管理员回复：</span>'+'</div>'+'<p>'+ unescape(data[i].reply_content)+'</p>'+'</div>';}
strHtml+='</li>';}
$(listDiv).html(strHtml);},error:function(XMLHttpRequest,textStatus,errorThrown){$(listDiv).html('<p style="line-height:35px;text-align:center;border:1px solid #f7f7f7;">暂无评论，快来抢沙发吧！</p>');}});}}
function initCKPlayer(boxId,videoSrc,playerSrc){var flashvars={f:videoSrc,c:0,loaded:'loadedHandler'};var video=[videoSrc];CKobject.embed(playerSrc,boxId,'video_v1','100%','100%',false,flashvars,video);}
$(function(){$("a[id^='top_']").click(function(){$("a[id^='top_']").removeClass("homecur");$(this).addClass("homecur");});});